const app = document.querySelector('#app');
const footer = () => document.querySelector('#footer').innerHTML;
const services = [
  ['Cloud Migration','Seamless transition to high-performance cloud environments offering maximum flexibility and data accessibility.'],
  ['Managed Support','24/7 proactive monitoring and expert technical assistance ensuring your infrastructure runs without interruption.'],
  ['Cybersecurity Services','Enterprise-grade encryption and threat detection protocols designed for maximum resilience against modern digital risks.'],
  ['Network Engineering','Optimized network design ensuring low latency and high-speed internal communication for your entire team.'],
  ['Redundant Backup','Automated business continuity solutions that safeguard your data with multiple layers of cloud and local redundancy.'],
  ['IT Consulting','Expert strategic guidance helping your business leverage technology as a competitive advantage for long-term growth.']
];
const serviceCards = services.map(([title,text],i) => `<article class="service-card"><span>0${i+1}</span><h3>${title}</h3><p>${text}</p><button class="learn">Learn More <b>→</b></button></article>`).join('');
function home(){return `<section class="hero"><div class="hero-inner"><p class="eyebrow badge">ENTERPRISE IT SPECIALISTS</p><h1>Technology Solutions<br>Without Limits</h1><p class="lede">Empowering small businesses and local organizations with premium managed IT solutions, advanced cybersecurity, and seamless cloud integration. We eliminate complexity so you can focus on what matters most.</p><div class="actions"><a class="button" href="#/services">Our Services</a><button class="button outline nav-contact">Request Support</button></div></div></section><section class="section services-intro"><div class="section-heading"><p class="eyebrow">WHAT WE DO</p><h2>Advanced IT Solutions</h2><p>Enterprise-grade technology services tailored for small businesses and local organizations without compromise.</p></div><div class="service-grid">${serviceCards}</div></section><section class="automation"><div><p class="eyebrow">CONNECTED LIVING</p><h2>Intelligent Home<br>Automation</h2></div><ul><li>Home & Office Networking</li><li>Smart Shading</li><li>Integrated Security</li><li>Voice-Activated Control</li></ul></section><section class="section excellence"><div class="section-heading"><p class="eyebrow">THE LIMITLESS STANDARD</p><h2>Engineered for Excellence</h2><p>Our managed IT solutions are built on a foundation of reliability and precision, ensuring your business stays ahead of the curve.</p></div><div class="reasons">${[['01','Expert Professionals','Our team consists of senior engineers with decades of combined enterprise experience.'],['02','Fast Response','We guarantee rapid incident mitigation and 24/7 proactive system monitoring.'],['03','Affordable Pricing','Cost-effective enterprise technology delivered at price points built for growth.'],['04','Certified Team','Elite certifications across major infrastructure and cybersecurity providers.'],['05','Guaranteed Care','Total satisfaction commitment on every project and support ticket we handle.']].map(x=>`<article><strong>${x[0]}</strong><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div><blockquote>“The integration of our cloud infrastructure has transformed our efficiency. Limitless delivered a high-tech solution that is both secure and incredibly fast.”<cite>— SARAH JENKINS, CTO AT TECHFLOW SOLUTIONS</cite></blockquote></section>${newsletter()}${footer()}`}
function newsletter(){return `<section class="newsletter"><p class="eyebrow">STAY AHEAD</p><h2>Secure Your Growth</h2><p>Enterprise-grade security meets high-tech precision. Join our network for exclusive technology insights and strategic IT updates tailored for small businesses.</p><form id="newsletter-form"><input required type="email" placeholder="Email Address" aria-label="Email Address"><button class="button">Join</button></form><p class="form-message" aria-live="polite"></p></section>`}
const plan=(name,price,items,featured=false)=>`<article class="plan ${featured?'featured':''}"><h3>${name}</h3><strong>${price}</strong><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul><button class="button nav-contact">${name==='Enterprise'?'Contact Us':'Get Started'}</button></article>`;
const mini=(name,items)=>`<article class="mini-service"><h3>${name}</h3><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul><button class="text-button nav-contact">Request a Quote →</button></article>`;
function servicesPage(){return `<section class="page-hero"><p class="eyebrow">SCALABLE BY DESIGN</p><h1>Managed IT Plans</h1><p>Choose the level of technology support that fits your business goals. Scalable solutions for growth-minded companies.</p></section><section class="plans">${plan('Essential Care','$299 <small>/Month</small>',['24/7 System Monitoring','Help Desk Over-the-Phone Support','Monthly Health Reports'])}${plan('Professional Care','$599 <small>/month</small>',['Everything in Essential','Advanced Threat Protection','Cloud Workspace Management','Managed Disaster Recovery','Priority Remote Support','Quarterly Business Reviews'],true)}${plan('Enterprise','Custom <small>Quote</small>',['Everything in Professional','Dedicated Technical Manager','24/7 Security Operations (SOC)','Unlimited On-site Support','Custom Infrastructure Design'])}</section><section class="section services-list"><div class="section-heading"><p class="eyebrow">BEYOND THE BASICS</p><h2>Services & Solutions</h2><p>Explore our comprehensive range of IT services designed to protect, connect, and empower your small business.</p></div><div class="mini-grid">${mini('Cybersecurity',['Firewall Configuration · $199','Endpoint Security · From $99','Password Manager · $49','Security Assessment · $149'])}${mini('Backup & Recovery',['PC Backup','Server Backup','Disaster Recovery','Cloud Backup','Starting at · $149'])}${mini('Networking',['Wi-Fi Installation · $99','Router Installation · $99','Network Optimization · $129','Switch Installation · $149'])}${mini('Smart Office',['Printer Setup','VoIP Phones','Conference Rooms','Automation','Starting at · $99'])}${mini('Microsoft 365 & Cloud',['Microsoft 365 Setup · $99','Outlook & Email Setup · $59','Cloud Migration · Starting at $199','Azure Cloud Setup · Starting at $199','Microsoft Intune · Starting at $149'])}</div></section>${footer()}`}
function about(){return `<section class="page-hero about-hero"><p class="eyebrow">THE MISSION</p><h1>Empowering the Edge</h1><div class="mission"><p>We believe that technology should be a force for growth, not a burden. Limitless Technology Solutions was founded on the principle that small businesses deserve the same high-end infrastructure and security as their larger counterparts.</p><p>Our mission is to bridge the digital divide through fast, smart IT solutions. We provide managed support and cybersecurity that prioritizes speed and reliability, ensuring your business stays ahead of the curve in an ever-evolving technological landscape.</p></div></section><section class="section team"><div class="section-heading"><p class="eyebrow">OUR PEOPLE</p><h2>Meet the Experts</h2></div><div class="team-grid">${[['Alex Vance','Lead Cybersecurity Architect'],['Sarah Jenkins','Cloud Solutions Specialist'],['Marcus Chen','IT Infrastructure Lead'],['Elena Rodriguez','Home Automation Specialist']].map((x,i)=>`<article class="person"><div class="avatar a${i}"><span>${x[0].split(' ').map(y=>y[0]).join('')}</span></div><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></section>${footer()}`}
function render(){let path=location.hash.replace('#','')||'/'; app.innerHTML=path==='/services'?servicesPage():path==='/about'?about():home(); bind(); window.scrollTo({top:0,behavior:'instant'});}
function bind(){document.querySelectorAll('.nav-contact,.learn').forEach(x=>x.addEventListener('click',()=>document.querySelector('#contact-modal').showModal()));document.querySelectorAll('.modal-close').forEach(x=>x.addEventListener('click',()=>document.querySelector('#contact-modal').close()));document.querySelector('#newsletter-form')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.nextElementSibling.textContent='Thanks — you’re on the list.';e.currentTarget.reset()});}
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('.form-message').textContent='Thanks — your request has been received.';e.currentTarget.reset()});
const drawer=document.querySelector('.drawer'),scrim=document.querySelector('.scrim'); const closeDrawer=()=>{drawer.classList.remove('open');scrim.classList.remove('open');drawer.setAttribute('aria-hidden','true')}; document.querySelector('.menu-button').addEventListener('click',()=>{drawer.classList.add('open');scrim.classList.add('open');drawer.setAttribute('aria-hidden','false')});document.querySelector('.drawer-close').addEventListener('click',closeDrawer);scrim.addEventListener('click',closeDrawer);drawer.addEventListener('click',e=>{if(e.target.tagName==='A')closeDrawer()});
window.addEventListener('hashchange',render);render();
